name: scrape

on:
  workflow_dispatch:
    inputs:
      site:
        description: "site to scrape"
        default: "halfclub"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      DEBIAN_FRONTEND: noninteractive
      NEEDRESTART_MODE: a
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: playwright install --with-deps chromium
      - run: python main.py ${{ inputs.site }}
